DROP DATABASE IF EXISTS malak;
CREATE DATABASE malak DEFAULT CHARSET utf8;
GRANT ALL PRIVILEGES ON malak.* TO 'malak'@'localhost' IDENTIFIED BY 'malak';
GRANT ALL PRIVILEGES ON malak.* TO 'malak'@'%' IDENTIFIED BY 'malak';
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS `test`;
CREATE TABLE `test` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `pracodawcy`;
CREATE TABLE `pracodawcy` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(255) NOT NULL UNIQUE,
  `teczka` BOOLEAN DEFAULT FALSE,
  `teczka_uwagi` VARCHAR(255) DEFAULT NULL,
  `ocena` BOOLEAN DEFAULT FALSE,
  `ocena_uwagi` VARCHAR(255) DEFAULT NULL,
  `szkolenia_okresowe` BOOLEAN DEFAULT FALSE,
  `szkolenia_okresowe_uwagi` VARCHAR(255) DEFAULT NULL,
  `szkolenia_pracodawcy` BOOLEAN DEFAULT FALSE,
  `szkolenia_pracodawcy_data` DATETIME DEFAULT NULL,
  `szkolenia_pracodawcy_uwagi` VARCHAR(255) DEFAULT NULL,
  `odziezowka` BOOLEAN DEFAULT FALSE,
  `odziezowka_uwagi` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

